name: docs

on:
  push:
    branches:
      - main
      - fergus/docs

concurrency:
  # cancels when a PR gets updated
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  docs:
    name: Build and publish
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Setup data directories
        run: |
          wget "https://www.star.bristol.ac.uk/fergus/spectral-fitting/ci-data/1E-1048-5937.tar"
          mkdir ex-datadir
          tar -xf 1E-1048-5937.tar -C ex-datadir/
      - name: Build documentation
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.add("Plots")
            Pkg.add("UnicodePlots")
            Pkg.add("BenchmarkTools")
            Pkg.add("Surrogates")
            Pkg.add("Turing")
            Pkg.add("StatsPlots")
            Pkg.add(url = "https://github.com/astro-group-bristol/LibXSPEC_jll.jl#master")
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --color=yes -tauto --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}